### ISSUE TITLE
有打印成功or失败的回调api吗?

### ISSUE THREAD

**Issue by dengshenkk** [denghao123/Print.js#3]
有这个需求,打印成功后不能二次打印!

**Comment by denghao123** [comment]
> 有这个需求,打印成功后不能二次打印!

你好，
1. 关于不能二次打印问题，我使用chrome / IE可以重复调起打印设备。你换个浏览器或刷新试试？
2. 关于回调的问题，网上有一些资料参考https://stackoverflow.com/questions/18325025/how-to-detect-window-print-finish。 主要在讨论打印前和后的回调，暂时没查到打印成功or失败的区分办法。
经测试，打印过程中，js是被阻塞的，可以这样粗暴处理：

```
startPrint();
window.print();
endPrint();
```

**Comment by dengshenkk** [comment]
@denghao123 "打印成功后就不能再次打印" 这个是我的需求,并不是bug! 所以需要一个回调状态来记录是否已打印... 不过目前看来不借助其他方式是实现不了了. 谢谢你!

**Comment by denghao123** [comment]
> @denghao123 "打印成功后就不能再次打印" 这个是我的需求,并不是bug! 所以需要一个回调状态来记录是否已打印... 不过目前看来不借助其他方式是实现不了了. 谢谢你!

sorry，审题失误。
我刚添加了2个回调方法onStart()和onEnd()，文档已经更换，你可以试试。不过只是笼统的回调，并不能判断到底用户有没有打印成功。Good Luck!
